"use client";
import { useEffect,useRef,useState } from "react"; import { useRouter } from "next/navigation"; import { AnimatePresence,motion,useReducedMotion } from "framer-motion"; import { Card,Button,PageMotion } from "@/components/ui"; import { questions,riskBand } from "@/data/questions"; import { useStore } from "@/lib/store"; import { track } from "@/lib/track";
export default function Home(){const s=useStore(),r=useRouter(),[index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),startAt=useRef(Date.now()),viewTracked=useRef(false),reduced=useReducedMotion();
 useEffect(()=>{if(!s.ready||viewTracked.current)return;viewTracked.current=true;track("session_start",{},1);track(s.started?"quiz_start":"intro_view",{},1)},[s.ready,s.started]);
 useEffect(()=>{const entered=Date.now();return()=>track("page_exit",{durationMs:Date.now()-entered},1)},[]);
 const begin=()=>{s.start();setIndex(0);startAt.current=Date.now();track("cta_click",{id:"intro_start",label:"체크 시작하기"},1);track("quiz_start",{},1)};
 const choose=(value:number)=>{if(selected!==null)return;setSelected(value);const q=questions[index];s.answer(q.id,value);track("quiz_answer",{qid:q.id,value,elapsedMs:Date.now()-startAt.current},1);setTimeout(()=>{if(index===7){const score=Object.values({...s.answers,[q.id]:value}).reduce((a,b)=>a+b,0);s.completeQuiz();track("quiz_complete",{score,riskBand:riskBand(score)},1);r.push(score<=2?"/low-risk":"/result")}else{setIndex(i=>i+1);setSelected(null);startAt.current=Date.now()}},250)};
 if(!s.ready)return null;if(!s.started)return <PageMotion><Card className="stack-24"><div className="stack"><h1>1분 수면 무호흡 위험도 체크</h1><p className="muted">8개의 간단한 질문으로 수면 무호흡 위험도를 확인해 보세요.<br/>약 1분이면 완료할 수 있습니다.</p></div><Button onClick={begin} aria-label="체크 시작하기">체크 시작하기</Button></Card></PageMotion>;
 const q=questions[index];return <AnimatePresence mode="wait"><motion.div key={q.id} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={reduced?{opacity:1}:{opacity:0}} transition={reduced?{duration:0}:{duration:.22,ease:[.22,1,.36,1]}}><Card className="stack-24"><div className="quiz-head"><h1>{q.title}</h1><span className="caption">{index+1} / 8</span></div>{q.caption&&<p className="caption">{q.caption}</p>}<div className="choices"><button className={`choice ${selected===1?"selected":""}`} onClick={()=>choose(1)} aria-label={`${q.title} 예`}>예</button><button className={`choice ${selected===0?"selected":""}`} onClick={()=>choose(0)} aria-label={`${q.title} 아니오`}>아니오</button></div></Card></motion.div></AnimatePresence>}
